### ISSUE TITLE
Negative values cause high brightness on Rainbow

### ISSUE THREAD

**Issue by nkotilainen** [pimoroni/flotilla-rockpool#1]
Temperature readings can go negative, causing issues with Rainbow colours and invert function for example, as seen in the attached photos:
![screen shot 2016-01-07 at 8 23 52 pm](https://cloud.githubusercontent.com/assets/881168/12178885/99f95a8a-b57c-11e5-9e67-2e1f85ad3d7c.png)
![p1200968](https://cloud.githubusercontent.com/assets/881168/12178740/c53ef2f0-b57b-11e5-8425-4f88261294be.JPG)

**Comment by Gadgetoid** [comment]
:D Haha! Thanks!

How cold does it get outside? I'm trying to determine a sensible temperature range to clamp the sensor to. Either +/- 50 degrees, or +/- 100 degrees would be sensible since these values scale nicely to the 0/1 scale that Rockpool uses internally.

I'm also working on some front-end jiggery pokery to actually display the value, in degrees C, that the temperature sensor is reading- for sanity's sake!

**Comment by Gadgetoid** [comment]
Sensor maxes out at -40, and +40 is probably more than enough in Flotilla for anyone not setting out to injure themselves. So the range has since been clamped at +-40.
